// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebChess.Data;

namespace WebChess.Migrations
{
    [DbContext(typeof(WebChessContext))]
    partial class WebChessContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebChess.Models.ChessGame", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gameType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pgn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("playerBlack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("playerWhite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("winner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ChessGame");
                });
#pragma warning restore 612, 618
        }
    }
}
